# Generated by Django 5.1.4 on 2024-12-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'Books'), (2, 'SchoolBooks'), (3, 'Writting Instruments')], verbose_name='Category')),
                ('description', models.CharField(max_length=300, verbose_name='Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Available')),
                ('pimage', models.ImageField(upload_to='images')),
                ('offer_price', models.IntegerField(default=0)),
            ],
        ),
    ]
