# Generated by Django 5.1.4 on 2025-01-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_firsttofifth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lkgukg',
            new_name='Lkgukg1',
        ),
    ]
