# Generated by Django 5.1.4 on 2025-01-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_lkgukg_lkgukg1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firsttofifth',
        ),
    ]
