# Generated by Django 5.1.4 on 2025-01-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biography',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Firsttofifth',
        ),
        migrations.DeleteModel(
            name='Lkg1',
        ),
        migrations.DeleteModel(
            name='Schoolbook',
        ),
        migrations.DeleteModel(
            name='Sixthtotenth',
        ),
        migrations.DeleteModel(
            name='Storybooks',
        ),
        migrations.DeleteModel(
            name='Writting',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
